from pathlib import Path
from datetime import datetime
from jinja2 import Template

from state.shared_state import MASState
from tools.grammar_check_tool import grammar_check
from observability.logger import log_event

AGENT_NAME = "ReportGenerator"
OUTPUT_PATH = "output/shortlist_report.html"

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>CV Screening Report — {{ job_title }}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Segoe UI', Tahoma, sans-serif;
      background: #f4f6f9;
      color: #1a1a2e;
      padding: 40px 20px;
    }
    .container { max-width: 860px; margin: auto; }
    h1 { font-size: 26px; color: #0f3460; border-bottom: 3px solid #0f3460; padding-bottom: 12px; margin-bottom: 8px; }
    .meta { color: #666; font-size: 14px; margin-bottom: 28px; }
    .summary {
      display: flex; gap: 24px;
      background: #fff; border-radius: 10px;
      padding: 20px 28px; margin-bottom: 32px;
      box-shadow: 0 1px 6px rgba(0,0,0,0.08);
    }
    .summary-item { text-align: center; }
    .summary-item .num { font-size: 36px; font-weight: 700; }
    .summary-item .label { font-size: 13px; color: #777; margin-top: 2px; }
    .num-total  { color: #0f3460; }
    .num-short  { color: #27ae60; }
    .num-reject { color: #e74c3c; }
    .card {
      background: #fff; border-radius: 10px;
      padding: 22px 26px; margin-bottom: 16px;
      box-shadow: 0 1px 5px rgba(0,0,0,0.07);
      border-left: 5px solid #ccc;
      position: relative;
    }
    .card.shortlisted { border-left-color: #27ae60; }
    .card.rejected    { border-left-color: #e74c3c; }
    .card-header { display: flex; justify-content: space-between; align-items: flex-start; }
    .candidate-name { font-size: 18px; font-weight: 600; }
    .score-badge {
      font-size: 22px; font-weight: 700;
      min-width: 70px; text-align: right;
      color: #0f3460;
    }
    .rank-label { font-size: 12px; color: #999; margin-top: 2px; }
    .status-pill {
      display: inline-block; padding: 3px 12px;
      border-radius: 20px; font-size: 12px; font-weight: 600;
      margin-top: 6px;
    }
    .pill-shortlisted { background: #e8f8f0; color: #1e8449; }
    .pill-rejected    { background: #fdecea; color: #c0392b; }
    .email { font-size: 13px; color: #888; margin-top: 4px; }
    .reasoning { font-size: 14px; color: #555; margin-top: 12px; font-style: italic; border-top: 1px solid #f0f0f0; padding-top: 10px; }
    .grammar-note { font-size: 12px; color: #aaa; margin-top: 8px; text-align: right; }
    .footer { text-align: center; font-size: 13px; color: #bbb; margin-top: 40px; }
  </style>
</head>
<body>
<div class="container">
  <h1>📋 CV Screening Report</h1>
  <div class="meta">
    <strong>Job Title:</strong> {{ job_title }} &nbsp;|&nbsp;
    <strong>Generated:</strong> {{ generated_at }} &nbsp;|&nbsp;
    <strong>Grammar issues corrected:</strong> {{ grammar_issues }}
  </div>

  <div class="summary">
    <div class="summary-item"><div class="num num-total">{{ total }}</div><div class="label">Total Candidates</div></div>
    <div class="summary-item"><div class="num num-short">{{ shortlisted }}</div><div class="label">Shortlisted</div></div>
    <div class="summary-item"><div class="num num-reject">{{ rejected }}</div><div class="label">Rejected</div></div>
  </div>

  {% for candidate in candidates %}
  <div class="card {{ candidate.status | lower }}">
    <div class="card-header">
      <div>
        <div class="candidate-name">{{ candidate.name }}</div>
        <span class="status-pill pill-{{ candidate.status | lower }}">{{ candidate.status }}</span>
        {% if candidate.email %}<div class="email">📧 {{ candidate.email }}</div>{% endif %}
      </div>
      <div>
        <div class="score-badge">{{ candidate.score }}<span style="font-size:14px;color:#999">/100</span></div>
        <div class="rank-label">Rank #{{ candidate.rank }}</div>
      </div>
    </div>
    {% if candidate.reasoning %}
    <div class="reasoning">{{ candidate.reasoning }}</div>
    {% endif %}
  </div>
  {% endfor %}

  <div class="footer">Generated by CV Screener MAS · Agent 4: Report Generator</div>
</div>
</body>
</html>"""


def run_report_generator(state: MASState) -> MASState:
    """
    Agent 4 node for LangGraph.

    Steps:
      1. Collects all reasoning text from ranked candidates.
      2. Calls grammar_check tool (free LanguageTool API).
      3. Applies corrected text back to candidates.
      4. Renders Jinja2 HTML template with all candidate data.
      5. Writes report to output/shortlist_report.html.

    Args:
        state: The shared MAS state containing ranked_candidates.

    Returns:
        Updated state with report_path set.
    """
    log_event(AGENT_NAME, "agent_start", message="Starting report generation")

    ranked = state["ranked_candidates"]
    shortlisted = sum(1 for c in ranked if c["status"] == "Shortlisted")

    # Collect all reasoning text
    all_reasoning = " ".join(
        c["reasoning"] for c in ranked if c.get("reasoning", "").strip()
    )

    # Grammar check via tool
    grammar_issues = 0
    corrected_reasoning_map: dict[str, str] = {}

    log_event(
        AGENT_NAME, "tool_call", tool_name="grammar_check",
        inputs={"text_length": len(all_reasoning), "candidates": len(ranked)},
    )

    try:
        result = grammar_check(all_reasoning)
        grammar_issues = result["issues_found"]

        log_event(
            AGENT_NAME, "tool_call", tool_name="grammar_check",
            outputs={"issues_found": grammar_issues},
            message=f"Grammar check complete — {grammar_issues} issue(s) found",
        )

        # Re-run grammar check per candidate for individual correction
        for candidate in ranked:
            raw = candidate.get("reasoning", "").strip()
            if raw:
                try:
                    per_result = grammar_check(raw)
                    corrected_reasoning_map[candidate["name"]] = per_result["corrected_text"]
                except RuntimeError:
                    corrected_reasoning_map[candidate["name"]] = raw
            else:
                corrected_reasoning_map[candidate["name"]] = raw

    except RuntimeError as e:
        log_event(AGENT_NAME, "error", message=f"Grammar check failed — skipping: {e}")
        state["errors"].append(f"Grammar check skipped: {e}")
        for candidate in ranked:
            corrected_reasoning_map[candidate["name"]] = candidate.get("reasoning", "")

    # Apply corrected reasoning to candidates for the template
    for candidate in ranked:
        candidate["reasoning"] = corrected_reasoning_map.get(
            candidate["name"], candidate.get("reasoning", "")
        )

    # Render HTML
    template = Template(HTML_TEMPLATE)
    html = template.render(
        job_title="Software Engineer",
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
        total=len(ranked),
        shortlisted=shortlisted,
        rejected=len(ranked) - shortlisted,
        grammar_issues=grammar_issues,
        candidates=ranked,
    )

    # Write report
    Path(OUTPUT_PATH).parent.mkdir(parents=True, exist_ok=True)
    Path(OUTPUT_PATH).write_text(html, encoding="utf-8")

    state["report_path"] = OUTPUT_PATH
    state["logs"].append(f"ReportGenerator: Report written to {OUTPUT_PATH}")

    log_event(
        AGENT_NAME, "agent_end",
        outputs={"report_path": OUTPUT_PATH, "shortlisted": shortlisted},
        message=f"Report generated — {shortlisted}/{len(ranked)} shortlisted",
    )

    return state